#pragma config(Hubs, S1, HTMotor, HTMotor, HTServo, HTMotor)
#pragma config(Sensor, S1, , sensorI2CMuxController)
#pragma config(Sensor, S2, gyro, sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3, IRSeeker, sensorHiTechnicIRSeeker1200)
#pragma config(Motor, mtr_S1_C1_1, rightMotor, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_2, leftMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor, mtr_S1_C4_1, slide, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C4_2, intake, tmotorTetrix, openLoop)
#pragma config(Servo, srvo_S1_C3_1, gripper, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <DriverCM.h>

/*----------------------------------------------------------------------------------------------------

 ______  _______ _______ _______ _       ________________        _______    _______        ________________ _       _______ _______ _______         _______ 
(  __  \(  ____ (  ____ (  ____ ( (    /(  ____ \__   __/\     /(  ____ \  (  ___  )\     /\__   __(  ___  | (    /(  ___  |       |  ___  )\     /(  ____ \
| (  \  ) (    \/ (    \/ (    \/  \  ( | (    \/  ) (  | )   ( | (    \/  | (   ) | )   ( |  ) (  | (   ) |  \  ( | (   ) | () () | (   ) | )   ( | (    \/
| |   ) | (__   | (__   | (__   |   \ | | (_____   | |  | |   | | (__      | (___) | |   | |  | |  | |   | |   \ | | |   | | || || | |   | | |   | | (_____ 
| |   | |  __)  |  __)  |  __)  | (\ \) (_____  )  | |  ( (   ) )  __)     |  ___  | |   | |  | |  | |   | | (\ \) | |   | | |(_)| | |   | | |   | (_____  )
| |   ) | (     | (     | (     | | \   |     ) |  | |   \ \_/ /| (        | (   ) | |   | |  | |  | |   | | | \   | |   | | |   | | |   | | |   | |     ) |
| (__/  ) (____/\ )     | (____/\ )  \  /\____) |__) (___ \   / | (____/\  | )   ( | (___) |  | |  | (___) | )  \  | (___) | )   ( | (___) | (___) /\____) |
(______/(_______//      (_______//    )_)_______)_______/  \_/  (_______/  |/     \(_______)  )_(  (_______)/    )_|_______)/     \(_______|_______)_______)
                                                                                                                                                            

Goals of the defensive autonomous:
 1. Knock over kickstand to release balls                    (30 Points)
 2. Prevent opposing team from placing ball in center goal   (60 Points Blocked)
 3. Just in general get in the way                           (? Points Blocked)
How goals are accomplished
 1. Start from ground start point
 2. Drive foward a bit
 3. Detect IR beacon
 4. Knock over kickstand based on center rotation
 5. Turn, and park in front of opposing center goal
For a diagram of the intended routes, look under the Defensive Autonomous folder

----------------------------------------------------------------------------------------------------*/

const int normalPower = 75;

//Beginning constants
const int distToSensePoint = 100;

//Sensor values given for various center rotations
//See images in Defensive Autonomous folder
const int mode1Sensor = 5;
const int mode2Sensor = 4;
const int mode3Sensor = -1;//default

//Mode 1 constants
const int mode1Turn1 = 25;
const int mode1Drive1 = 50;
const int mode1Turn2 = 20;
const int mode1Drive2 = 175;
const int mode1Turn3 = 20;
const int mode1Drive3 = 45;

//Mode 2 constants
const int mode2Turn1 = 45;
const int mode2Drive1 = 25;
const int mode2Turn2 = 45;
const int mode2Drive2 = 200;
const int mode2Turn3 = 45;
const int mode2Drive3 = 75;

//Mode 3 constants
const int mode3Drive1 = 45;
const int mode3Turn1 = 25;
const int mode3Drive2 = 100;
const int mode3Turn2 = 45;
const int mode3Drive3 = 65;

//Raising constants
const int fullRaise = 45;

void mode1()
{
	runMotorByCm(leftMotor, normalPower, mode1Turn1);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode1Drive1);
	runMotorByCm(leftMotor, normalPower, mode1Turn2);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode1Drive2);
	runMotorByCm(leftMotor, normalPower, mode1Turn3);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode1Drive3);
}

void mode2()
{
	runMotorByCm(leftMotor, normalPower, mode2Turn1);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode2Drive1);
	runMotorByCm(leftMotor, normalPower, mode2Turn2);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode2Drive2);
	runMotorByCm(leftMotor, normalPower, mode2Turn3);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode2Drive3);	
}

void mode3()
{
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode3Drive1);
	runMotorByCm(leftMotor, normalPower, mode3Turn1);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode3Drive2);
	runMotorByCm(leftMotor, normalPower, mode3Turn2);
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, mode3Drive3);		
}

task main()
{
	runTwoMotorsByCm(leftMotor, rightMotor, normalPower, distToSensePoint);
	switch(SensorValue[IRSeeker])
	{
	case mode1Sensor:
		mode1();
		break;

	case mode2Sensor:
		mode2();
		break;

	default:
		mode3();
		break;
	}
	runMotorByCm(slide, normalPower, fullRaise);//Raise slide to further defend high goal
}
